"""Signal history tracking, dedup, and resolution for trade signals.

Tracks every BUY/SELL signal generated by the system, deduplicates within
a configurable window, and resolves outcomes by checking actual prices
against stop-loss / take-profit levels.
"""

from __future__ import annotations

import json
import sqlite3
from datetime import timezone
from pathlib import Path
from typing import Any

# Dedup window: same ticker + action within this window = skip
DEDUP_WINDOW_HOURS = 4

# Resolution windows
RESOLVE_AFTER_HOURS_24H = 24
RESOLVE_AFTER_HOURS_72H = 72
EXPIRE_AFTER_DAYS = 7

BACKEND_DB_PATH = Path(__file__).resolve().parent.parent / "data" / "polstock_backend.db"


def _get_conn() -> sqlite3.Connection:
    BACKEND_DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(BACKEND_DB_PATH), timeout=30)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA busy_timeout=30000")
    conn.execute("PRAGMA synchronous=NORMAL")
    return conn


def init_signal_tables() -> None:
    """Create signal_history and portfolio tables if they don't exist."""
    conn = _get_conn()
    try:
        conn.executescript("""
            CREATE TABLE IF NOT EXISTS signal_history (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                ticker TEXT NOT NULL,
                action TEXT NOT NULL CHECK (action IN ('BUY', 'SELL')),
                signal_strength REAL NOT NULL,
                price_at_signal REAL NOT NULL,
                stop_loss REAL,
                take_profit REAL,
                risk_reward REAL,
                timeframe TEXT,
                reasons_json TEXT,
                event_headline TEXT,
                event_source TEXT,
                signal_source TEXT DEFAULT 'auto',
                price_after_24h REAL,
                price_after_72h REAL,
                actual_return_24h REAL,
                actual_return_72h REAL,
                outcome TEXT DEFAULT 'pending' CHECK (outcome IN ('pending', 'win', 'loss', 'expired')),
                resolved_at TEXT,
                created_at TEXT DEFAULT (datetime('now'))
            );

            CREATE INDEX IF NOT EXISTS idx_signal_history_ticker
                ON signal_history(ticker);
            CREATE INDEX IF NOT EXISTS idx_signal_history_outcome
                ON signal_history(outcome);
            CREATE INDEX IF NOT EXISTS idx_signal_history_created
                ON signal_history(created_at);
            CREATE INDEX IF NOT EXISTS idx_signal_history_action
                ON signal_history(action);

            CREATE TABLE IF NOT EXISTS portfolio (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                ticker TEXT NOT NULL,
                direction TEXT NOT NULL CHECK (direction IN ('long', 'short')),
                entry_price REAL NOT NULL,
                shares INTEGER NOT NULL DEFAULT 0,
                stop_loss REAL,
                take_profit REAL,
                signal_id INTEGER REFERENCES signal_history(id),
                sector TEXT,
                status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'closed')),
                exit_price REAL,
                exit_date TEXT,
                pnl REAL,
                pnl_pct REAL,
                entry_date TEXT DEFAULT (datetime('now'))
            );

            CREATE INDEX IF NOT EXISTS idx_portfolio_status
                ON portfolio(status);
            CREATE INDEX IF NOT EXISTS idx_portfolio_ticker
                ON portfolio(ticker);

            CREATE TABLE IF NOT EXISTS pinned_tickers (
                ticker TEXT PRIMARY KEY,
                pinned_at TEXT DEFAULT (datetime('now'))
            );
        """)
        conn.commit()
    finally:
        conn.close()


def log_signal(
    ticker: str,
    action: str,
    signal_strength: float,
    price_at_signal: float,
    stop_loss: float | None = None,
    take_profit: float | None = None,
    risk_reward: float | None = None,
    timeframe: str | None = None,
    reasons: list[str] | None = None,
    event_headline: str | None = None,
    event_source: str | None = None,
    signal_source: str = "auto",
) -> dict[str, Any] | None:
    """Log a trade signal to signal_history. Returns the logged record or None if deduped.

    Dedup: same ticker + action within DEDUP_WINDOW_HOURS = skip.
    """
    if action not in ("BUY", "SELL"):
        return None

    conn = _get_conn()
    try:
        # Dedup check — use SQLite datetime format for comparison
        from datetime import datetime, timedelta
        cutoff_dt = datetime.utcnow() - timedelta(hours=DEDUP_WINDOW_HOURS)
        cutoff = cutoff_dt.strftime("%Y-%m-%d %H:%M:%S")
        row = conn.execute(
            "SELECT id FROM signal_history WHERE ticker = ? AND action = ? AND created_at > ? ORDER BY created_at DESC LIMIT 1",
            (ticker, action, cutoff),
        ).fetchone()
        if row:
            return None  # deduped

        reasons_json = json.dumps(reasons or [])
        cur = conn.execute(
            """INSERT INTO signal_history
               (ticker, action, signal_strength, price_at_signal, stop_loss, take_profit,
                risk_reward, timeframe, reasons_json, event_headline, event_source, signal_source)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (ticker, action, signal_strength, price_at_signal, stop_loss, take_profit,
             risk_reward, timeframe, reasons_json, event_headline, event_source, signal_source),
        )
        conn.commit()
        signal_id = cur.lastrowid

        return {
            "id": signal_id,
            "ticker": ticker,
            "action": action,
            "signal_strength": signal_strength,
            "price_at_signal": price_at_signal,
            "stop_loss": stop_loss,
            "take_profit": take_profit,
            "risk_reward": risk_reward,
            "timeframe": timeframe,
            "reasons": reasons or [],
            "event_headline": event_headline,
            "event_source": event_source,
            "signal_source": signal_source,
            "outcome": "pending",
            "created_at": datetime.now(timezone.utc).isoformat(),
        }
    finally:
        conn.close()


def get_signal_history(
    limit: int = 50,
    action: str | None = None,
    ticker: str | None = None,
    outcome: str | None = None,
) -> list[dict[str, Any]]:
    """Query signal history with optional filters."""
    conn = _get_conn()
    try:
        query = "SELECT * FROM signal_history WHERE 1=1"
        params: list[Any] = []
        if action:
            query += " AND action = ?"
            params.append(action)
        if ticker:
            query += " AND ticker = ?"
            params.append(ticker)
        if outcome:
            query += " AND outcome = ?"
            params.append(outcome)
        query += " ORDER BY created_at DESC LIMIT ?"
        params.append(limit)

        rows = conn.execute(query, params).fetchall()
        cols = [d[0] for d in conn.execute("SELECT * FROM signal_history LIMIT 0").description]
        results = []
        for row in rows:
            record = dict(zip(cols, row))
            try:
                record["reasons"] = json.loads(record.get("reasons_json") or "[]")
            except (json.JSONDecodeError, TypeError):
                record["reasons"] = []
            record.pop("reasons_json", None)
            results.append(record)
        return results
    finally:
        conn.close()


def get_signal_stats() -> dict[str, Any]:
    """Get aggregate signal statistics."""
    conn = _get_conn()
    try:
        total = conn.execute("SELECT COUNT(*) FROM signal_history").fetchone()[0]
        pending = conn.execute("SELECT COUNT(*) FROM signal_history WHERE outcome = 'pending'").fetchone()[0]
        wins = conn.execute("SELECT COUNT(*) FROM signal_history WHERE outcome = 'win'").fetchone()[0]
        losses = conn.execute("SELECT COUNT(*) FROM signal_history WHERE outcome = 'loss'").fetchone()[0]
        expired = conn.execute("SELECT COUNT(*) FROM signal_history WHERE outcome = 'expired'").fetchone()[0]

        resolved = wins + losses
        hit_rate = wins / resolved if resolved > 0 else None

        return {
            "total_signals": total,
            "pending": pending,
            "wins": wins,
            "losses": losses,
            "expired": expired,
            "resolved": resolved,
            "hit_rate": round(hit_rate, 3) if hit_rate is not None else None,
        }
    finally:
        conn.close()


def resolve_signals(
    current_prices: dict[str, float],
) -> list[dict[str, Any]]:
    """Resolve pending signals against current prices.

    A signal is:
    - 'win' if price hits take_profit
    - 'loss' if price hits stop_loss
    - 'expired' if older than EXPIRE_AFTER_DAYS without hitting either

    Args:
        current_prices: dict of ticker -> current price

    Returns list of resolved signal records.
    """
    conn = _get_conn()
    resolved: list[dict[str, Any]] = []
    try:
        from datetime import datetime, timedelta
        expire_cutoff_dt = datetime.utcnow() - timedelta(days=EXPIRE_AFTER_DAYS)
        expire_cutoff = expire_cutoff_dt.strftime("%Y-%m-%d %H:%M:%S")
        rows = conn.execute(
            "SELECT id, ticker, action, price_at_signal, stop_loss, take_profit, created_at "
            "FROM signal_history WHERE outcome = 'pending' ORDER BY created_at DESC"
        ).fetchall()

        for row in rows:
            sig_id, ticker, action, price_at, sl, tp, created = row
            current = current_prices.get(ticker)
            if current is None:
                continue

            outcome = None
            # Check win/loss
            if action == "BUY":
                if tp and current >= tp:
                    outcome = "win"
                elif sl and current <= sl:
                    outcome = "loss"
            elif action == "SELL":
                if tp and current <= tp:
                    outcome = "win"
                elif sl and current >= sl:
                    outcome = "loss"

            # Check expiry
            if outcome is None and created and created < expire_cutoff:
                outcome = "expired"

            # Update 24h/72h prices
            if created:
                created_dt = datetime.fromisoformat(created).replace(tzinfo=timezone.utc)
                age_hours = (datetime.now(timezone.utc) - created_dt).total_seconds() / 3600
                if age_hours >= RESOLVE_AFTER_HOURS_24H:
                    conn.execute(
                        "UPDATE signal_history SET price_after_24h = ?, actual_return_24h = ? WHERE id = ? AND price_after_24h IS NULL",
                        (current, round((current - price_at) / price_at * 100, 3) if price_at else None, sig_id),
                    )
                if age_hours >= RESOLVE_AFTER_HOURS_72H:
                    conn.execute(
                        "UPDATE signal_history SET price_after_72h = ?, actual_return_72h = ? WHERE id = ? AND price_after_72h IS NULL",
                        (current, round((current - price_at) / price_at * 100, 3) if price_at else None, sig_id),
                    )

            if outcome:
                conn.execute(
                    "UPDATE signal_history SET outcome = ?, resolved_at = datetime('now') WHERE id = ?",
                    (outcome, sig_id),
                )
                resolved.append({"id": sig_id, "ticker": ticker, "action": action, "outcome": outcome})

        conn.commit()
        return resolved
    finally:
        conn.close()


def get_pinned_tickers() -> set[str]:
    """Return set of manually pinned tickers."""
    conn = _get_conn()
    try:
        init_signal_tables()
        rows = conn.execute("SELECT ticker FROM pinned_tickers").fetchall()
        return {r[0] for r in rows}
    finally:
        conn.close()


def pin_ticker(ticker: str) -> bool:
    """Pin a ticker. Returns True if newly pinned."""
    conn = _get_conn()
    try:
        init_signal_tables()
        cur = conn.execute(
            "INSERT OR IGNORE INTO pinned_tickers (ticker) VALUES (?)", (ticker,)
        )
        conn.commit()
        return cur.rowcount > 0
    finally:
        conn.close()


def unpin_ticker(ticker: str) -> bool:
    """Unpin a ticker. Returns True if was pinned."""
    conn = _get_conn()
    try:
        init_signal_tables()
        cur = conn.execute("DELETE FROM pinned_tickers WHERE ticker = ?", (ticker,))
        conn.commit()
        return cur.rowcount > 0
    finally:
        conn.close()


def get_portfolio_tickers() -> set[str]:
    """Return set of tickers with open portfolio positions."""
    conn = _get_conn()
    try:
        init_signal_tables()
        rows = conn.execute(
            "SELECT DISTINCT ticker FROM portfolio WHERE status = 'open'"
        ).fetchall()
        return {r[0] for r in rows}
    finally:
        conn.close()
